### ISSUE TITLE
tensooflow包里面的这个类报错 

### ISSUE THREAD

**Issue by liming1010** [sjsdfg/dl4j-tutorials#1]
你好，我是初学者，很感谢出一个视频。tensooflow包里面的这个类报错

**Comment by sjsdfg** [comment]
@liming1010 
这个程序我自己已经运行过，且没有问题。
emmm, 你这个提问没有给我任何报错信息还有你的运行环境信息，你真的让我很头疼好吧，那我就只能猜测了。
这个类是严重依赖于`lombok`的一个类。
如果你是`IDEA`，请在`setting -> plugin`里面下载对应的插件
如果是`eclipse`，在官网下载对应的jar包，双击安装
