### ISSUE TITLE
jnicudart.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by xiaozw123** [sjsdfg/dl4j-tutorials#7]
请问下我在win7上用 cuda-9.2  cuDNN7.1.4，其他的代码跟网上一样
但是运行lesson6/LenetMnistExample.java 报错
jnicudart.dll: Can't find dependent libraries

**Comment by sjsdfg** [comment]
电脑重启依旧是同样报错？

确认所有 cuda 相关的路径已经加入到环境变量里面了么

使用`where jnicudart.dll` 找一下路径

**Comment by xiaozw123** [comment]
cuda安装成功了 
C:\Users\Administrator\.javacpp\cache\cuda-9.2-7.1-1.4.2-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnicuda.dll: Can't find dependent libraries
这个目录下也有jnicuda.dll这个文件
我的显卡是geforce 800M不知道跟显卡有没有关系

**Comment by sjsdfg** [comment]
这种事情一般都和显卡和安装的 cuda 环境变量有关
